const date = new Date()
        const nap = date.getDay()
        const óra = date.getHours()
        const perc = date.getMinutes()

        let muvtori = document.getElementById('művtöri')
let korus = document.getElementById('kórus')
let gitar = document.getElementById('gitár')
let continuo = document.getElementById('conti')
let mzt = document.getElementById('magyarZir')
let kamara = document.getElementById('kamara')
let szolf = document.getElementById('szolf')
let gitZen = document.getElementById('gitárzenekar')

        let hétfő = document.getElementById("Mon")
        let kedd = document.getElementById("Tue")
        let szerda = document.getElementById("Wed")
        let csütörtök = document.getElementById("Thu")
        let péntek = document.getElementById("Fri")
        let szombat = document.getElementById("Sat")
        let vasárnap = document.getElementById("Sun")